spring:
  application:
    name: PicheTestTask

  datasource:
    url: jdbc:postgresql://localhost:5432/piche
    username: root
    password: 1q2w3e4r
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: none



server:
  port: 8080